# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20150426_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(upload_to='forum/upload/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='num_posts',
            field=models.IntegerField(default=0, verbose_name='Number of Posts'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='num_threads',
            field=models.IntegerField(default=0, verbose_name='Number of Threads'),
        ),
        migrations.AlterField(
            model_name='forumgroup',
            name='format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('plain_text', 'Plain Text'), ('extended_html', 'Extended HTML'), ('sanitized_html', 'Sanitized HTML'), ('template', 'Django Template'), ('html', 'HTML'), ('bbcode', 'BBcode'), ('magic_html', 'Magic HTML')], max_length=20),
        ),
        migrations.AlterField(
            model_name='forumgroup',
            name='post_redirect_delay',
            field=models.IntegerField(default=3, help_text='How long to show the successful post page, before redirecting.  Set to 0 to disable.'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='notify',
            field=models.CharField(choices=[('AL', 'Always Notify'), ('NV', 'Never Notify')], default='AL', max_length=2),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='show_avatars',
            field=models.BooleanField(default=True, help_text='Show that avatar images of users.'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='show_img',
            field=models.BooleanField(default=True, help_text='Show images in forum posts.', verbose_name='Show Images'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='show_sig',
            field=models.BooleanField(default=True, help_text='Show user signature after their posts.', verbose_name='Show Signature'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='show_simlies',
            field=models.BooleanField(default=True, help_text='Show smilies in forum posts.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck this box to make the post effectively disappear from the site.', verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Check this box if the post is inappropriate. A "This post has been removed" message will be displayed instead.', verbose_name='is removed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Check this box to flag as spam.', verbose_name='is spam'),
        ),
        migrations.AlterField(
            model_name='post',
            name='show_similies',
            field=models.BooleanField(default=True, help_text='Show smilies as icons for this post.'),
        ),
    ]
