# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20170710_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forumgroup',
            name='format',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('magic_html', 'Magic HTML'), ('extended_html', 'Extended HTML'), ('sanitized_html', 'Sanitized HTML'), ('template', 'Django Template'), ('html', 'HTML'), ('bbcode', 'BBcode'), ('plain_text', 'Plain Text')], max_length=20),
        ),
    ]
