# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usersocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_settings',
            field=models.CharField(choices=[('HI', 'Hide Email'), ('SW', 'Show Email'), ('HB', 'Use Web Form')], default='HI', max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Private'), ('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(default='New member', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='account',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('google_plus', 'Google Plus'), ('facebook', 'Facebook'), ('linkedin', 'Linked In'), ('pinterest', 'Pinterest')], max_length=20),
        ),
    ]
