# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20150813_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck this box to make the comment effectively disappear from the site.', verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Check this box to flag as spam.', verbose_name='is spam'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_url',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(verbose_name='Post Contents'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='entry',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edited'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(unique_for_date='posted'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PR', 'Pending Review'), ('PB', 'Published')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='visibility',
            field=models.CharField(choices=[('VI', 'Visible'), ('PR', 'Private')], default='VI', max_length=2),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag',
            field=models.CharField(max_length=100, verbose_name='flag'),
        ),
    ]
