# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170710_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='maillog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
