# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20170710_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='render',
            field=models.CharField(choices=[('magic_html', 'Magic HTML'), ('sanitized_html', 'Sanitized HTML'), ('extended_html', 'Extended HTML'), ('template', 'Django Template'), ('html', 'HTML'), ('plain_text', 'Plain Text'), ('bbcode', 'BBcode'), ('markdown', 'Markdown')], default='extended_html', max_length=30),
        ),
    ]
