# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20170714_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageblock',
            name='render',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('template', 'Django Template'), ('plain_text', 'Plain Text'), ('sanitized_html', 'Sanitized HTML'), ('bbcode', 'BBcode'), ('html', 'HTML'), ('magic_html', 'Magic HTML'), ('extended_html', 'Extended HTML')], default='extended_html', max_length=30),
        ),
    ]
