# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20150921_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images/gallery/%y/%m/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='scaled',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/gallery/scaled/%y/%m/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='images/gallery/thumbs/%y/%m/'),
        ),
    ]
