# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20141109_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='link_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Link Text (optional)'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link Url (optional)'),
        ),
    ]
